language: python
python:
 - "2.7"

matrix:
  include:
    - name: 3.7_bionic
      python: 3.7
      dist: bionic
      
    - name: 3.8_bionic
      python: 3.8
      dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-xlib scrot python-imaging xvfb 
  - sudo apt-get install -y zenity gcalctool gxmessage x11-utils gnumeric

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install .
 
script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - nosetests -v --with-coverage --cover-package=discogui .
 
after_success:
 - coveralls
