language: python
# python:
#  - "2.7"
#  - "3.6"

matrix:
  include:
    - name: 2.7_bionic
      python: 2.7
      dist: bionic

    - name: 3.7_bionic
      python: 3.7
      dist: bionic
      
    - name: 3.8_bionic
      python: 3.8
      dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scrot xvfb 
  - sudo apt-get install -y zenity gnome-calculator gxmessage x11-utils gnumeric

install:
 - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then PYTHON=python; else PYTHON=python3; fi
 - if [ ${TRAVIS_OS_NAME} == "windows" ]; then PYTHON=python; fi
 - $PYTHON -m pip install -r requirements-test.txt
 - $PYTHON -m pip install .
 
script:  
 - cd tests 
 - $PYTHON -m pytest -v .
 
