language: python
python:
 - "2.7"

matrix:
  include:
    - python: 3.7
      dist: xenial
      env: DIST="xenial"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-xlib scrot python-imaging xdotool xvfb 
  - sudo apt-get install -y zenity gcalctool gxmessage x11-utils gnumeric

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade https://github.com/pepijndevos/PyMouse/zipball/master
 - pip install --upgrade http://downloads.sourceforge.net/project/python-xlib/python-xlib/0.14/python-xlib-0.14.tar.gz
 - pip install --upgrade .
 
script:  
 - xauth add :0 . `mcookie`
 - cd tests 
 - nosetests -v --with-coverage --cover-package=discogui .
 
after_success:
 - coveralls
